"""test 3...

q

exit


Revision ID: 0acaea782b5d
Revises: a89ddeb62beb
Create Date: 2022-10-03 17:45:50.305602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acaea782b5d'
down_revision = 'a89ddeb62beb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
